### ISSUE TITLE
The Shape of Matrix

### ISSUE THREAD

**Issue by QueueRear** [FIGLAB/Super-Resolution-Dataset#1]
Hi @sven-mayer,
I think the "Matrix" column in `.csv` file is the image generated by touch screen, but the length and width information of the image seems not to be mentioned. Would you please tell me about that?

Best wishes,
QueueRear

**Comment by sven-mayer** [comment]
Dear @QueueRear,

please have look at this file https://github.com/FIGLAB/Super-Resolution-Dataset/blob/main/Showcase-Dataset.ipynb its explained in the example code `.reshape(49,37)` So the matrix is 49 by 37 pixels.

Hope this helps
Sven

**Comment by QueueRear** [comment]
I'm grateful for your reply. I apologize for not informing you earlier, but I did find the specifications soon after I proposed this issue. Please accept my apologies for any inconvenience caused.
