### ISSUE TITLE
The acquisition of capacitance images

### ISSUE THREAD

**Issue by QDZ123** [FIGLAB/Super-Resolution-Dataset#2]
Hi @sven-mayer,
I have read a lot of information but I am still confused about how capacitance images are obtained. Capacitive touch screens identify and locate touch points by detecting changes in capacitance. So, what does the pixel value of a capacitance image represent and how is it obtained? Would you please tell me about that?

Best wishes,
Qiao

**Comment by sven-mayer** [comment]
Dear @QDZ123,

Please see the documentation of Huy Viet Le http://huyle.de/blog/capacitive-images/ In his documentation, he explained how to flash and hack the kernel to get the capacitive matrix. While he explains it for a Nexus 5, it is the same for the Samsung Galaxy Tab S2 tablet that we used in this project.

If you have a Samsung Galaxy Tab S2 you can also use the pre-compiled kernel and instructions provided in this repo: https://github.com/FIGLAB/3DHandPose 

Best
Sven
